name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      working-directory: build
      run: |
        apt-get install -y cmake qtbase5-dev 
        cmake ..
    - name: make
      working-directory: build
      run: make
    - name: make check
      working-directory: build
      run: make check
    - name: make distcheck
      working-directory: build
      run: make distcheck
